#!/bin/bash

echo "=========================================="
echo "Firebase Service Account Setup"
echo "=========================================="
echo ""
echo "1. Open this URL in your browser:"
echo "   https://console.firebase.google.com/project/divtrack-6a09d/settings/serviceaccounts/adminsdk"
echo ""
echo "2. Click 'Generate New Private Key'"
echo "3. Click 'Generate Key' in the confirmation dialog"
echo "4. A JSON file will download (divtrack-6a09d-firebase-adminsdk-xxxxx.json)"
echo ""
echo "5. Open the downloaded JSON file and copy these values:"
echo "   - private_key"
echo "   - client_email"
echo ""
echo "6. Edit backend/.env and add:"
echo '   FIREBASE_PRIVATE_KEY="-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----\n"'
echo "   FIREBASE_CLIENT_EMAIL=firebase-adminsdk-xxxxx@divtrack-6a09d.iam.gserviceaccount.com"
echo ""
echo "=========================================="
echo "Database is already set up with 196 items!"
echo "=========================================="
